"""All SQLAlchemy models, mirroring ESD §4. Import from here so Base.metadata
sees every table (Alembic autogenerate, tests)."""
from app.models.base import Base
from app.models.assessment import (
    AssessmentAnswer,
    AssessmentConversation,
    AssessmentMessage,
    CandidateQuestion,
    CandidateTechnicalQuestion,
    FunctionalSkillsReport,
    JobCompetency,
    ReportDimension,
    ReportSkillEvidence,
    TechnicalQuestion,
)
from app.models.bd import (
    CHANNELS,
    PROGRESS_FLAGS,
    PROGRESS_LABELS,
    SOCIAL_SOURCES,
    TENANT_PROSPECT,
    BDLead,
)
from app.models.billing import (
    CONSUMPTION_SUBUNITS,
    EVENT_COMPLETED,
    EVENT_GRANT,
    EVENT_INCOMPLETE,
    EVENT_NO_SHOW,
    EVENT_OLD_PROFILE_REVIEW,
    LEDGER_EVENT_TYPES,
    SUBSCRIPTION_STATUSES,
    SUBUNITS_PER_CREDIT,
    BillingTransaction,
    CreditLedgerEntry,
    OldProfileReview,
    PricingPlan,
    WebhookEvent,
)
from app.models.agent import (
    STATUS_FAILED,
    STATUS_PARTIAL,
    STATUS_SUCCESS,
    AgentExecutionTrace,
    AgentLearning,
)
from app.models.context import ContextChunk
from app.models.evidence import EvidenceClaim, EvidenceClaimLink, EvidenceItemRow
from app.models.project import CandidateProject
from app.models.candidate import (
    Candidate,
    CandidateTeamReview,
    Interview,
    JobCandidateLink,
    PipelineStatusEntry,
    Profile,
    VerificationRequest,
)
from app.models.company import Company, EmailTemplate, HiringManager
from app.models.compliance import (
    COMMERCIAL_DOCUMENT_TYPES,
    DOCUMENT_GROUPS,
    DOCUMENT_LABELS,
    DOCUMENT_TYPES,
    TAX_DOCUMENT_TYPES,
    ComplianceDocument,
)
from app.models.email_log import EMAIL_TYPES, EmailLog
from app.models.enums import (
    APPROVAL_CHAIN,
    ApprovalDecision,
    JobStatus,
    LinkSource,
    LLMProvider,
    LLMRoleHint,
    OTPChannel,
    PipelineStatus,
    Role,
    SubmittedVia,
    Tier,
    UserStatus,
    VerificationStatus,
)
from app.models.job import JDDraft, Job, JobApproval
from app.models.job_setup import (
    SWOT_AREAS,
    SWOT_STATUS_ACTIVE,
    SWOT_STATUS_COMPLETE,
    JobMatchingCategory,
    JobSwotIntake,
)
from app.models.proctoring import (
    ProctoringEvent,
    ProctoringReport,
    ProctoringSession,
)
from app.models.telemetry import TelemetryEvent
from app.models.tenant import AuditLog, LLMProviderKey, RolePermission, Tenant
from app.models.hiring import (
    CalibrationRecord,
    CompanyDNA,
    Evaluation,
    ReviewDisposition,
)
# The `company_dna` TABLE is mapped in app.models.hiring (migration 0059).
# This is the Layer 2 binding that records which version a job's scorecard was
# frozen against (migration 0060); it is a separate table, not a second
# mapping of that one.
from app.models.company_dna import JobCompanyDNABinding
from app.models.user import OTPChallenge, User

__all__ = [
    "Base",
    "APPROVAL_CHAIN",
    "ApprovalDecision",
    "BDLead",
    "CHANNELS",
    "AssessmentAnswer",
    "AssessmentConversation",
    "AssessmentMessage",
    "AuditLog",
    "BillingTransaction",
    "Candidate",
    "CandidateProject",
    "CandidateQuestion",
    "CandidateTeamReview",
    "CandidateTechnicalQuestion",
    "CONSUMPTION_SUBUNITS",
    "CreditLedgerEntry",
    "EVENT_COMPLETED",
    "EVENT_GRANT",
    "EVENT_INCOMPLETE",
    "EVENT_NO_SHOW",
    "EVENT_OLD_PROFILE_REVIEW",
    "LEDGER_EVENT_TYPES",
    "OldProfileReview",
    "PricingPlan",
    "SUBSCRIPTION_STATUSES",
    "SUBUNITS_PER_CREDIT",
    "WebhookEvent",
    "COMMERCIAL_DOCUMENT_TYPES",
    "Company",
    "ComplianceDocument",
    "DOCUMENT_GROUPS",
    "DOCUMENT_LABELS",
    "DOCUMENT_TYPES",
    "EMAIL_TYPES",
    "EmailLog",
    "EmailTemplate",
    "HiringManager",
    "FunctionalSkillsReport",
    "Interview",
    "Job",
    "JobApproval",
    "JobMatchingCategory",
    "JobSwotIntake",
    "SWOT_AREAS",
    "SWOT_STATUS_ACTIVE",
    "SWOT_STATUS_COMPLETE",
    "JobCandidateLink",
    "JobCompetency",
    "JobStatus",
    "LinkSource",
    "LLMProvider",
    "LLMProviderKey",
    "LLMRoleHint",
    "OTPChallenge",
    "OTPChannel",
    "PipelineStatus",
    "PipelineStatusEntry",
    "PROGRESS_FLAGS",
    "PROGRESS_LABELS",
    "Profile",
    "Role",
    "SOCIAL_SOURCES",
    "TENANT_PROSPECT",
    "ReportDimension",
    "ReportSkillEvidence",
    "RolePermission",
    "SubmittedVia",
    "TAX_DOCUMENT_TYPES",
    "AgentExecutionTrace",
    "CalibrationRecord",
    "CompanyDNA",
    "Evaluation",
    "ReviewDisposition",
    "JobCompanyDNABinding",
    "AgentLearning",
    "ContextChunk",
    "EvidenceClaim",
    "EvidenceClaimLink",
    "EvidenceItemRow",
    "STATUS_FAILED",
    "STATUS_PARTIAL",
    "STATUS_SUCCESS",
    "ProctoringEvent",
    "ProctoringReport",
    "ProctoringSession",
    "TelemetryEvent",
    "Tenant",
    "TechnicalQuestion",
    "Tier",
    "User",
    "UserStatus",
    "VerificationRequest",
]
