"""All SQLAlchemy models, mirroring ESD §4. Import from here so Base.metadata
sees every table (Alembic autogenerate, tests)."""
from app.models.base import Base
from app.models.assessment import (
    AssessmentConversation,
    AssessmentMessage,
    CandidateQuestion,
    FunctionalSkillsReport,
    JobCompetency,
    ReportDimension,
    TechnicalQuestion,
)
from app.models.bd import (
    CHANNELS,
    PROGRESS_FLAGS,
    PROGRESS_LABELS,
    SOCIAL_SOURCES,
    TENANT_PROSPECT,
    BDLead,
)
from app.models.billing import (
    CONSUMPTION_SUBUNITS,
    EVENT_COMPLETED,
    EVENT_GRANT,
    EVENT_INCOMPLETE,
    EVENT_NO_SHOW,
    EVENT_OLD_PROFILE_REVIEW,
    LEDGER_EVENT_TYPES,
    SUBSCRIPTION_STATUSES,
    SUBUNITS_PER_CREDIT,
    BillingTransaction,
    CreditLedgerEntry,
    OldProfileReview,
    PricingPlan,
    WebhookEvent,
)
from app.models.candidate import (
    Candidate,
    CandidateTeamReview,
    Interview,
    JobCandidateLink,
    PipelineStatusEntry,
    Profile,
    VerificationRequest,
)
from app.models.company import Company, EmailTemplate, HiringManager
from app.models.compliance import (
    COMMERCIAL_DOCUMENT_TYPES,
    DOCUMENT_GROUPS,
    DOCUMENT_LABELS,
    DOCUMENT_TYPES,
    TAX_DOCUMENT_TYPES,
    ComplianceDocument,
)
from app.models.email_log import EMAIL_TYPES, EmailLog
from app.models.enums import (
    APPROVAL_CHAIN,
    ApprovalDecision,
    JobStatus,
    LinkSource,
    LLMProvider,
    LLMRoleHint,
    OTPChannel,
    PipelineStatus,
    Role,
    SubmittedVia,
    Tier,
    UserStatus,
    VerificationStatus,
)
from app.models.job import Job, JobApproval
from app.models.tenant import AuditLog, LLMProviderKey, RolePermission, Tenant
from app.models.user import OTPChallenge, User

__all__ = [
    "Base",
    "APPROVAL_CHAIN",
    "ApprovalDecision",
    "BDLead",
    "CHANNELS",
    "AssessmentConversation",
    "AssessmentMessage",
    "AuditLog",
    "BillingTransaction",
    "Candidate",
    "CandidateQuestion",
    "CandidateTeamReview",
    "CONSUMPTION_SUBUNITS",
    "CreditLedgerEntry",
    "EVENT_COMPLETED",
    "EVENT_GRANT",
    "EVENT_INCOMPLETE",
    "EVENT_NO_SHOW",
    "EVENT_OLD_PROFILE_REVIEW",
    "LEDGER_EVENT_TYPES",
    "OldProfileReview",
    "PricingPlan",
    "SUBSCRIPTION_STATUSES",
    "SUBUNITS_PER_CREDIT",
    "WebhookEvent",
    "COMMERCIAL_DOCUMENT_TYPES",
    "Company",
    "ComplianceDocument",
    "DOCUMENT_GROUPS",
    "DOCUMENT_LABELS",
    "DOCUMENT_TYPES",
    "EMAIL_TYPES",
    "EmailLog",
    "EmailTemplate",
    "HiringManager",
    "FunctionalSkillsReport",
    "Interview",
    "Job",
    "JobApproval",
    "JobCandidateLink",
    "JobCompetency",
    "JobStatus",
    "LinkSource",
    "LLMProvider",
    "LLMProviderKey",
    "LLMRoleHint",
    "OTPChallenge",
    "OTPChannel",
    "PipelineStatus",
    "PipelineStatusEntry",
    "PROGRESS_FLAGS",
    "PROGRESS_LABELS",
    "Profile",
    "Role",
    "SOCIAL_SOURCES",
    "TENANT_PROSPECT",
    "ReportDimension",
    "RolePermission",
    "SubmittedVia",
    "TAX_DOCUMENT_TYPES",
    "Tenant",
    "TechnicalQuestion",
    "Tier",
    "User",
    "UserStatus",
    "VerificationRequest",
]
