"""The candidate's in-portal Updates feed (migration 0079, workflow section 14).

WHY THIS TABLE EXISTS AT ALL
------------------------------
Everything the product tells a candidate goes out by email and nowhere else.
A filtered message, a full inbox, a typo in an address a recruiter uploaded, a
spam folder -- any one of them and the candidate silently misses an assessment
invitation, an interview, or a request for information, and neither side ever
finds out. The workflow document puts it plainly: missing an email must not
mean missing an opportunity.

So every event that matters is ALSO written here, where the candidate can find
it by signing in. The feed is durable, per-candidate, and readable long after
an email would have scrolled away.

THIS IS NOT THE EMAIL LOG, AND MERGING THEM WOULD BE WRONG
------------------------------------------------------------
`email_log` answers "what did we send, to which address, and did it deliver".
It is an OUTBOUND DELIVERY record: it exists whether or not the recipient is a
ReadyPick account, it carries the exact copy that was sent for audit, and rows
in it are written for internal recipients too (the question-bank reminder goes
to a recruiter).

This table answers "what has happened to me, that I should know about". Not
every update has an email (a stage that mails nobody still belongs in the
feed), not every email has an update (nothing internal does), and the two have
different lifetimes and different readers. One table would force every future
event to invent an email it does not send, or force this feed to render an
audit record written for somebody else.

WHAT IS AND IS NOT IN AN UPDATE
---------------------------------
A title and a body, both written by the product from a fixed catalogue, plus
the identifiers needed to link back into the portal. NO SCORE, NO GRADE, NO
RANK and no number that describes the candidate: this is a client-facing
surface like any other and the no-numbers rule applies in full. Nothing here
is generated by a model, so there is no drafting failure that can leave a
candidate with a blank feed on the day their assessment invitation arrives.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, CreatedAtMixin, UUIDPKMixin


class CandidateUpdate(Base, UUIDPKMixin, CreatedAtMixin):
    __tablename__ = "candidate_updates"
    __table_args__ = (
        # The feed is always read newest-first for one candidate, and the
        # unread badge counts the same rows. One index serves both.
        Index(
            "ix_candidate_updates_feed",
            "candidate_id",
            "created_at",
        ),
    )

    candidate_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("candidates.id", ondelete="CASCADE"),
        nullable=False,
    )
    #: The client whose action produced this update, when there is one.
    #: Nullable because a candidate spans tenants and some updates (a profile
    #: reminder) belong to no client at all. NOT the RLS boundary -- the
    #: candidate portal filters by `candidate_id` and the policy mirrors the
    #: parent `candidates` row, exactly as `candidate_projects` does.
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE")
    )
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE")
    )
    job_candidate_link_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("job_candidate_links.id", ondelete="CASCADE")
    )

    #: What kind of thing happened, from `services/candidate_updates.KINDS`.
    #: A machine value so the UI can group and icon without parsing prose.
    kind: Mapped[str] = mapped_column(String(50), nullable=False)
    #: One line, written by the product. Never generated, never a model's words.
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    #: A sentence or two of context. Same rules as the title.
    body: Mapped[str] = mapped_column(Text, nullable=False)
    #: Where in the portal this leads, as a relative path. Relative rather than
    #: absolute so a stored row cannot become an off-site link, and nullable
    #: because some updates are information rather than an action.
    link_path: Mapped[str | None] = mapped_column(String(500))

    #: When the candidate opened the feed with this row in it. NULL is unread.
    #: A timestamp rather than a boolean: "unread" is derivable from it, and
    #: knowing WHEN somebody saw an interview invitation is the more useful of
    #: the two facts and cannot be recovered from a flag.
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    #: Whether the same event also went out by email. Rendered so a candidate
    #: reading the feed knows whether to go looking in their inbox for detail,
    #: and so support can answer "did you not get the email" without guessing.
    emailed: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
