"""Situating a chunk before it is embedded, without ever changing what it says.

RPN-AI-UP-001 W6.2. Anthropic's measured result: top-20 retrieval failure falls
from 5.7% to 3.7% with contextual embeddings, to 2.9% when the generated
context also reaches the lexical index, and to 1.9% with reranking on top. That
is the best measured chunking return available, and it fits this corpus almost
exactly: a resume chunk reading "Led migration to event driven architecture"
loses its employer, its dates and its seniority, and the prefix restores
precisely the provenance the evidence model depends on.

THE PREFIX IS MODEL OUTPUT AND NEVER BECOMES FACT
--------------------------------------------------
It lives in its OWN column, `context_chunks.context_prefix`, mirroring the
separation `candidate_projects` already draws between `ai_interpretation_json`
and `evidence_json`. Four layers never blur, and this is one of them.

The chunk's `content` column is untouched. Retrieval returns `content`, the
evidence ledger's `text_ref` points at `content`, and Siddhi cites `content`.
The prefix reaches exactly two places and no others:

  1. the string handed to the embedding model, and
  2. the `content_tsv` expression, so the lexical half gets the same benefit
     (migration 0091 redefines the generated column; it is still generated by
     Postgres, and `content` is still the only thing anyone reads).

`embedding_input` is the ONE function that joins them, and it returns a value
that is indexed and thrown away. Nothing in this module writes `content`.

IT IS HOSTILE INPUT PROCESSING, AND IT IS TREATED AS SUCH
----------------------------------------------------------
The document is a resume a candidate uploaded or a JD a client typed. An
injection in a PDF reaches a model by exactly the path an injection in a chat
message does, so:

  * the document passes `conversation_guardrails.inspect_answer` BEFORE it
    enters a prompt, and a REFUSED document gets no prefix at all -- the chunk
    is still indexed verbatim, so one poisoned paragraph costs the prefix and
    never the retrievability of the candidate's evidence;
  * the generated prefix passes `conversation_guardrails.inspect_agent_output`
    BEFORE it is stored, because a prefix is text a model wrote about a
    candidate and it is one join away from a prompt that grades them.

INDEX TIME ONLY, NEVER THE INTERACTIVE PATH
--------------------------------------------
One model call per changed chunk. That is affordable on `Route.LAMBDA`, where
`pickready.index_document` already runs and nobody is waiting, and it is not
affordable on a request handler. Putting it on one would spend the whole
interactive budget before generation started, which is the argument
`rag/context.compress` already makes for staying extractive.

LUNA, BECAUSE IT SITUATES AND DOES NOT JUDGE
---------------------------------------------
Task type `context_prefix`, model Luna. The prefix states where a passage sits
in its document. It forms no opinion, assigns no level and reaches no
conclusion. Putting Terra here would be a boundary violation dressed as an
upgrade, which is the same argument that keeps `claim_extraction` on Luna.

A FAILURE IS COUNTED, NEVER GUESSED
------------------------------------
Every path that cannot produce a prefix returns a `PrefixResult` carrying
`degraded=True` and a named reason, and the chunk is indexed with a NULL
prefix. A template prefix, or the chunk's own first sentence dressed as
generated context, would be output presented as generation.
"""
from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Sequence

from app.config import llm_providers
from app.core.config import get_settings
from app.prompts import registry
from app.services import conversation_guardrails
from app.services.llm_router import LLMUnavailableError, invoke_llm
from app.services.rag.context import CHARS_PER_TOKEN

logger = logging.getLogger(__name__)

#: The router task type. Registered in `config/llm_providers.MODEL_FOR_TASK`;
#: an unregistered type raises there rather than defaulting, which is the
#: behaviour that made a two-day `conversation_turn` outage visible.
TASK_TYPE = "context_prefix"

#: The prompt, loaded through the registry so a wording change is a versioned
#: diff rather than an invisible edit inside a Python string.
PROMPT_NAME = "context_prefix"

#: The tier this task MUST run on. Asserted against `MODEL_FOR_TASK` in
#: `tests/test_contextual_prefix.py` so a future registration on the reasoning
#: tier fails a test rather than passing review as an upgrade.
REQUIRED_MODEL = llm_providers.MODEL_LUNA

#: W6.2's stated window: 50 to 100 tokens of situating context. Both numbers
#: are substituted into the prompt AND the upper one is enforced below, so the
#: instruction and the validator cannot drift apart -- one rule implemented
#: twice is the fault `services/tiers.py` cost this platform.
#:
#: Only the CEILING is enforced. A prefix that comes back at forty tokens is
#: shorter than asked for and still situates the chunk; refusing it would trade
#: a useful prefix for none, which is a worse outcome than a terse one.
#: `MAX_PREFIX_CHARS` is converted through `rag/context.CHARS_PER_TOKEN` rather
#: than restated in characters, so the two budgets in this package stay
#: comparable and only one estimate of a token exists.
MIN_PREFIX_TOKENS = 50
MAX_PREFIX_TOKENS = 100
MAX_PREFIX_CHARS = MAX_PREFIX_TOKENS * CHARS_PER_TOKEN

#: How much of the whole document the model is shown as the situating frame.
#: A ceiling rather than the whole text: a long resume would otherwise put a
#: five-figure token count on every chunk of it, and the parts of a document
#: that situate a passage are its headings and its structure, which survive
#: this window.
MAX_DOCUMENT_CHARS = 24_000

#: The chunk itself is sent whole. A chunk is already bounded by
#: `chunking.TARGET_CHARS`, and the one case that exceeds it -- a single
#: sentence longer than the target, kept whole deliberately -- is exactly the
#: case where cutting it would ask the model to situate half a sentence. This
#: ceiling exists only to refuse something pathological.
MAX_CHUNK_CHARS = 8_000

#: Concurrent prefix calls per document. Bounded because a forty-chunk resume
#: would otherwise open forty sockets at once against a per-minute token pool,
#: and the failure mode of that is a burst of rate limits which the router
#: classifies correctly and which still costs the whole document its prefixes.
MAX_CONCURRENT_CALLS = 4

#: Named reasons, because these land in a log line and in an operator's count.
#: Two spellings of one condition are two conditions to the person reading.
REASON_DISABLED = "disabled"
REASON_EMPTY_INPUT = "empty_input"
REASON_OVERSIZED_INPUT = "oversized_input"
REASON_GUARDRAIL_INPUT = "guardrail_input"
REASON_GUARDRAIL_OUTPUT = "guardrail_output"
REASON_MODEL_UNAVAILABLE = "model_unavailable"
REASON_EMPTY_OUTPUT = "empty_output"
REASON_OVER_LENGTH = "over_length"

#: The `Settings` attribute holding the feature's deployment state, populated
#: from `RETRIEVAL_CONTEXTUAL_PREFIX`.
SETTING_ATTR = "retrieval_contextual_prefix"


@dataclass(frozen=True)
class PrefixResult:
    """One chunk's situating context, or an honest account of its absence."""

    #: The generated prefix, or None. None is a legitimate outcome: the chunk
    #: is indexed with a NULL `context_prefix` and is retrievable exactly as it
    #: was before this feature existed.
    prefix: str | None = None
    #: Which model wrote it. Stored on the row for the same reason
    #: `embedding_model` is: the text of a prefix says nothing about what
    #: produced it, and this index will outlive more than one model id.
    model: str | None = None
    generated_at: datetime | None = None
    #: True whenever a prefix was wanted and not produced. False when the
    #: deployment has the feature off, which is a choice rather than a failure,
    #: and False on success.
    degraded: bool = False
    reason: str | None = None

    @property
    def has_prefix(self) -> bool:
        return bool(self.prefix)


def enabled() -> bool:
    """Whether this deployment generates prefixes at index time.

    Deployment data, one value per deployment. An absent or non-boolean setting
    RAISES rather than defaulting: a deployment that believes it is running
    contextual retrieval and is not would show no symptom at all, because a
    chunk with no prefix retrieves perfectly well and simply retrieves worse.
    """
    value = getattr(get_settings(), SETTING_ATTR, None)
    if not isinstance(value, bool):
        raise ValueError(
            f"{SETTING_ATTR.upper()} must be a boolean, not {value!r}. It is "
            "deployment data and has no default here, because a silently "
            "disabled prefix pass is indistinguishable from a working one."
        )
    return value


def embedding_input(prefix: str | None, content: str) -> str:
    """The string that gets EMBEDDED. Never the string that gets stored.

    The one place the generated prefix and the verbatim chunk are joined, and
    the value it returns is handed to the embedding model and discarded. If a
    second join ever appears, one of them will eventually be written to
    `content`, and a model's summary will have become a candidate's own words.
    """
    situating = " ".join(str(prefix or "").split())
    verbatim = str(content or "")
    if not situating:
        return verbatim
    return f"{situating}\n\n{verbatim}"


def _clean(value: str) -> str:
    return " ".join(str(value or "").split())


def _bounded(text: str) -> str | None:
    """Hold the prefix inside its window without cutting a sentence in half.

    Over-length output is trimmed back to the last SENTENCE boundary inside the
    ceiling, and refused outright when there is none. The product's standing
    rule is to validate and regenerate complete prose rather than truncate to a
    limit, and a prefix ending mid-clause is text a model will complete from
    its own priors when it reads the chunk back.
    """
    if len(text) <= MAX_PREFIX_CHARS:
        return text
    window = text[:MAX_PREFIX_CHARS]
    cut = max(window.rfind(". "), window.rfind("! "), window.rfind("? "))
    if cut <= 0:
        return None
    return window[: cut + 1].strip() or None


def _validate(raw: str) -> tuple[str | None, str | None]:
    """(prefix, reason). Exactly one of the two is None."""
    text = _clean(raw)
    if not text:
        return None, REASON_EMPTY_OUTPUT

    # The output guard drops offending SENTENCES rather than editing them, and
    # returns its own continuation line when everything went. That line is a
    # candidate-facing pleasantry, not a situating context, so it is refused
    # here rather than stored as though the model had written it.
    guarded = _clean(conversation_guardrails.inspect_agent_output(text))
    if not guarded or guarded == _clean(conversation_guardrails.SAFE_FALLBACK):
        return None, REASON_GUARDRAIL_OUTPUT
    if guarded != text:
        logger.warning("rag.contextual.prefix_sanitised chars=%d", len(text))

    bounded = _bounded(guarded)
    if bounded is None:
        return None, REASON_OVER_LENGTH
    return bounded, None


async def _generate_one(
    *, document: str, chunk_content: str, source_type: str, model: str
) -> PrefixResult:
    """One model call for one chunk. Never raises for a vendor problem."""
    chunk = str(chunk_content or "").strip()
    if not chunk:
        return PrefixResult(degraded=True, reason=REASON_EMPTY_INPUT)
    if len(chunk) > MAX_CHUNK_CHARS:
        return PrefixResult(degraded=True, reason=REASON_OVERSIZED_INPUT)

    messages = [
        {
            "role": "system",
            "content": registry.render(
                PROMPT_NAME,
                source_type=source_type,
                min_tokens=MIN_PREFIX_TOKENS,
                max_tokens=MAX_PREFIX_TOKENS,
            ),
        },
        {
            "role": "user",
            "content": (
                "<document>\n"
                f"{document}\n"
                "</document>\n\n"
                "<chunk>\n"
                f"{chunk}\n"
                "</chunk>"
            ),
        },
    ]
    try:
        raw = await invoke_llm(TASK_TYPE, messages)
    except LLMUnavailableError as exc:
        # Counted, not raised. A provider outage during indexing must not lose
        # the chunk's text: `index_document` already writes a chunk with a NULL
        # embedding for the same reason, and a chunk with a NULL prefix is the
        # product's behaviour before this feature existed.
        logger.warning(
            "rag.contextual.unavailable source_type=%s err=%s",
            source_type,
            type(exc).__name__,
        )
        return PrefixResult(degraded=True, reason=REASON_MODEL_UNAVAILABLE)

    prefix, reason = _validate(raw)
    if prefix is None:
        return PrefixResult(degraded=True, reason=reason)
    return PrefixResult(
        prefix=prefix,
        model=model,
        generated_at=datetime.now(timezone.utc),
    )


async def generate_prefixes(
    *, document: str, chunk_contents: Sequence[str], source_type: str
) -> list[PrefixResult]:
    """A situating prefix for each chunk of one document, in the same order.

    Returns exactly `len(chunk_contents)` results, always. A caller zipping
    these against its chunks must never receive a short list: that would attach
    one chunk's prefix to the next chunk's row, which is the same silent
    misattribution `embeddings._embed_batch` sorts by explicit index to avoid.
    """
    if not chunk_contents:
        return []
    if not enabled():
        return [PrefixResult(reason=REASON_DISABLED) for _ in chunk_contents]

    guard = conversation_guardrails.inspect_answer(document)
    if not guard.allowed:
        # Refused, and the refusal is per DOCUMENT rather than per chunk: the
        # situating frame is the thing that was poisoned. The chunks are still
        # indexed verbatim by the caller.
        logger.warning(
            "rag.contextual.input_refused source_type=%s violation=%s",
            source_type,
            guard.violation,
        )
        return [
            PrefixResult(degraded=True, reason=REASON_GUARDRAIL_INPUT)
            for _ in chunk_contents
        ]

    frame = _clean(guard.sanitized)[:MAX_DOCUMENT_CHARS]
    if not frame:
        return [
            PrefixResult(degraded=True, reason=REASON_EMPTY_INPUT)
            for _ in chunk_contents
        ]

    # Resolved once. `model_for` raises for an unregistered task type, and it
    # is better that it raises here, once, than that every chunk records a
    # model id this module guessed.
    model = llm_providers.model_for(TASK_TYPE)
    limit = asyncio.Semaphore(MAX_CONCURRENT_CALLS)

    async def _bounded_call(content: str) -> PrefixResult:
        async with limit:
            return await _generate_one(
                document=frame,
                chunk_content=content,
                source_type=source_type,
                model=model,
            )

    return list(
        await asyncio.gather(*(_bounded_call(content) for content in chunk_contents))
    )
