"""Writing documents into the chunk index, and keeping it honest as they change.

INCREMENTAL BY CONTENT HASH, NOT BY TIMESTAMP
----------------------------------------------
A JD edited in its third paragraph re-embeds one chunk. The mechanism is a
comparison of `content_sha256` against what is already stored, and the reason it
is a hash rather than an `updated_at` comparison is the rule this codebase
learned expensively: a timestamp is not evidence that work happened. A stamp
says something ran. A hash says the text is the text.

RE-INDEXING IS AN UPSERT, AND THAT IS LOAD-BEARING
---------------------------------------------------
Keyed on (source_type, source_id, ordinal), so running the indexer twice over
one document produces one copy. An append-only indexer produces two, and the
consequence is not merely wasted space: retrieval returns the same sentence
under two ids, and an agent reading it counts the second as corroboration of the
first. Stale trailing chunks -- what a document that got SHORTER left behind --
are deleted in the same transaction, because an orphan chunk is a sentence that
is no longer in the document still being retrieved as though it were.

EMBEDDING FAILURE DOES NOT LOSE THE TEXT
----------------------------------------
Chunks are written with a NULL embedding when the embedding service is
unreachable, and the keyword half of retrieval keeps working on them because
`content_tsv` is generated by Postgres and never depended on the model. A later
pass fills them in. The alternative -- refusing to index until the GPU service
answers -- means a resume uploaded during an outage is invisible to retrieval
forever, since nothing would ever ask again.
"""
from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.services.embeddings import EmbeddingError, embed
from app.services.rag import chunking

logger = logging.getLogger(__name__)

#: Chunks per embedding request. The endpoint is a batched GPU service; one call
#: per chunk would make indexing one resume forty round trips.
EMBED_BATCH_SIZE = 100


@dataclass(frozen=True)
class IndexResult:
    """What one indexing pass actually did, in terms a caller can act on."""

    source_id: uuid.UUID
    source_type: str
    written: int = 0
    unchanged: int = 0
    deleted: int = 0
    embedded: int = 0
    #: True when text was indexed with no vector because embedding failed. The
    #: chunk is searchable by keyword; it is not searchable semantically until a
    #: backfill runs. Counted rather than raised, and never silent.
    degraded: bool = False

    @property
    def total(self) -> int:
        return self.written + self.unchanged


def _vector_literal(vector: list[float]) -> str:
    return "[" + ",".join(f"{value:.7f}" for value in vector) + "]"


async def _embed_batched(texts: list[str]) -> tuple[list[list[float] | None], bool]:
    """Embed in batches; a failed batch yields None vectors, never an exception.

    Per-batch rather than all-or-nothing: one 503 in the middle of a long resume
    should cost that batch's vectors, not the whole document's.
    """
    vectors: list[list[float] | None] = []
    degraded = False
    for start in range(0, len(texts), EMBED_BATCH_SIZE):
        batch = texts[start : start + EMBED_BATCH_SIZE]
        try:
            vectors.extend(await embed(batch))
        except EmbeddingError as exc:
            logger.warning(
                "rag.index.embedding_failed batch=%d size=%d err=%s",
                start // EMBED_BATCH_SIZE,
                len(batch),
                type(exc).__name__,
            )
            vectors.extend([None] * len(batch))
            degraded = True
    return vectors, degraded


async def index_document(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    source_type: str,
    source_id: uuid.UUID,
    document: str,
    chunks: list[chunking.Chunk] | None = None,
) -> IndexResult:
    """Index one document, re-embedding only what changed.

    `chunks` is accepted pre-split for the assessment path, where the unit is a
    question-and-answer pair rather than a slice of prose and the caller already
    holds the pairs.
    """
    version = chunking.source_version(document)
    pieces = chunks if chunks is not None else chunking.chunk_text(
        document, source_type=source_type
    )

    existing = {
        row.ordinal: row.content_sha256
        for row in (
            await session.execute(
                text(
                    """
                    SELECT ordinal, content_sha256
                      FROM context_chunks
                     WHERE source_type = :source_type AND source_id = :source_id
                    """
                ),
                {"source_type": source_type, "source_id": str(source_id)},
            )
        )
    }

    changed = [
        piece
        for piece in pieces
        if existing.get(piece.ordinal) != piece.content_sha256
    ]
    unchanged = len(pieces) - len(changed)

    vectors: list[list[float] | None] = []
    degraded = False
    if changed:
        vectors, degraded = await _embed_batched([piece.content for piece in changed])

    for piece, vector in zip(changed, vectors or [None] * len(changed)):
        await session.execute(
            text(
                """
                INSERT INTO context_chunks (
                    tenant_id, source_type, source_id, source_version,
                    section_type, ordinal, content, content_sha256, embedding,
                    updated_at
                ) VALUES (
                    :tenant_id, :source_type, :source_id, :source_version,
                    :section_type, :ordinal, :content, :content_sha256,
                    CAST(:embedding AS vector), now()
                )
                ON CONFLICT (source_type, source_id, ordinal) DO UPDATE SET
                    source_version = EXCLUDED.source_version,
                    section_type   = EXCLUDED.section_type,
                    content        = EXCLUDED.content,
                    content_sha256 = EXCLUDED.content_sha256,
                    embedding      = EXCLUDED.embedding,
                    updated_at     = now()
                """
            ),
            {
                "tenant_id": str(tenant_id),
                "source_type": source_type,
                "source_id": str(source_id),
                "source_version": version,
                "section_type": piece.section_type,
                "ordinal": piece.ordinal,
                "content": piece.content,
                "content_sha256": piece.content_sha256,
                "embedding": _vector_literal(vector) if vector else None,
            },
        )

    # A document that got shorter leaves chunks behind. They are no longer in the
    # text and must stop being retrievable as though they were.
    deleted = (
        await session.execute(
            text(
                """
                DELETE FROM context_chunks
                 WHERE source_type = :source_type
                   AND source_id = :source_id
                   AND ordinal >= :count
                """
            ),
            {
                "source_type": source_type,
                "source_id": str(source_id),
                "count": len(pieces),
            },
        )
    ).rowcount or 0

    # Version is stamped on every surviving row, including the ones whose own
    # text did not change: an unchanged paragraph still belongs to the new
    # version of the document, and leaving it stamped with the old one would
    # make a version filter hide it.
    if unchanged:
        await session.execute(
            text(
                """
                UPDATE context_chunks
                   SET source_version = :version
                 WHERE source_type = :source_type
                   AND source_id = :source_id
                   AND source_version <> :version
                """
            ),
            {
                "version": version,
                "source_type": source_type,
                "source_id": str(source_id),
            },
        )

    return IndexResult(
        source_id=source_id,
        source_type=source_type,
        written=len(changed),
        unchanged=unchanged,
        deleted=deleted,
        embedded=sum(1 for vector in vectors if vector),
        degraded=degraded,
    )


async def backfill_missing_embeddings(
    session: AsyncSession, *, limit: int = 200
) -> int:
    """Fill vectors for chunks indexed while the embedding service was down.

    The other half of the degradation path. Without something that asks the
    TABLE which rows have no vector, a chunk written during an outage is
    keyword-searchable forever and semantically invisible forever, and nothing
    anywhere would report it.
    """
    rows = list(
        await session.execute(
            text(
                """
                SELECT id, content FROM context_chunks
                 WHERE embedding IS NULL
                 ORDER BY created_at
                 LIMIT :limit
                """
            ),
            {"limit": limit},
        )
    )
    if not rows:
        return 0

    vectors, _ = await _embed_batched([row.content for row in rows])
    filled = 0
    for row, vector in zip(rows, vectors):
        if not vector:
            continue
        await session.execute(
            text(
                "UPDATE context_chunks SET embedding = CAST(:embedding AS vector), "
                "updated_at = now() WHERE id = :id"
            ),
            {"embedding": _vector_literal(vector), "id": str(row.id)},
        )
        filled += 1
    return filled
