import { JsonLd } from "@/components/json-ld";
import { SITE_DESCRIPTION, SITE_NAME, SITE_URL } from "@/lib/site";

/**
 * Site-level structured data: who publishes this site, and what the site is.
 *
 * TWO NODES, ONE GRAPH. `Organization` describes Vivekium and `WebSite`
 * describes readypick.ai. They are emitted together in an `@graph` so the
 * WebSite can name its publisher by `@id` rather than repeating the
 * organisation inline, which is what stops a consumer reading two different
 * organisations off one page.
 *
 * EVERY FIELD IS VERIFIABLE FROM THIS REPOSITORY, AND NOTHING ELSE IS CLAIMED.
 *
 *  - `name` and `description` are the product name and the site-wide meta
 *    description, both from `lib/site.ts`.
 *  - `url` is the canonical origin.
 *  - `logo` is `/icon`, the 512x512 PNG generated by `app/icon.tsx`. It was
 *    `public/icon.png` until 2026-09-20, when that raster was deleted for
 *    carrying the PREVIOUS logo. Google's Organization logo guidance wants an
 *    image at least 112x112, which 512 clears, and the generated route is
 *    really served. An invented path here would produce a logo property
 *    pointing at a 404, which is worse than no logo property, so this one
 *    moved with the file rather than after it.
 *  - `parentOrganization` is Varpitech LLP, which the public site
 *    footer states on every page ("A Varpitech LLP product"). It
 *    is the one corporate fact this site actually publishes.
 *  - `inLanguage` is "en", which is what `<html lang>` declares.
 *
 * WHAT IS DELIBERATELY ABSENT, and none of it is an oversight:
 *
 *  - No `address`. The Terms name Hyderabad courts in a governing-law clause.
 *    A jurisdiction is not a registered office, and turning one into a
 *    PostalAddress would be inventing a business location.
 *  - No `telephone`, no `foundingDate`, no `numberOfEmployees`, no
 *    `aggregateRating`, no `review`. None of them exists anywhere in this
 *    repository, and a rating in particular would be a number attached to a
 *    claim nobody made.
 *  - No `sameAs`. The site links to no social profile, so there is no profile
 *    to corroborate the organisation with.
 *  - No `contactPoint`. The published contact address is an individual's
 *    personal mailbox. It is already visible in the footer and on the legal
 *    pages, but asserting it in structured data as the ORGANISATION's official
 *    contact point is a claim the owner should make deliberately, with a
 *    mailbox on the product's own domain.
 *  - No `potentialAction` / SearchAction. There is no site-wide search
 *    endpoint, and Google retired the sitelinks searchbox in any case.
 *
 * WHERE IT RENDERS. `app/(public)/layout.tsx` frames every public page except
 * `/`, which sits at the app root and carries its own frame; both render this,
 * and no page renders it twice. `/apply` is outside both and is left alone: it
 * carries JobPosting data about one role at one employer, and adding the
 * platform's own Organization beside it would put two organisations on a page
 * whose whole subject is the hiring company.
 *
 * `/employers/{slug}` IS inside the group, so it carries this node AND the
 * employer's own Organization. That is why both nodes name themselves with an
 * `@id`: two Organization objects on one page, one the platform and one the
 * hiring company, is an ambiguity a consumer resolves by guessing unless each
 * one is identified.
 */
export function SiteJsonLd() {
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@graph": [
          {
            "@type": "Organization",
            "@id": `${SITE_URL}/#organization`,
            name: SITE_NAME,
            url: SITE_URL,
            logo: `${SITE_URL}/icon`,
            description: SITE_DESCRIPTION,
            parentOrganization: {
              "@type": "Organization",
              name: "Varpitech LLP",
            },
          },
          {
            "@type": "WebSite",
            "@id": `${SITE_URL}/#website`,
            name: SITE_NAME,
            url: SITE_URL,
            description: SITE_DESCRIPTION,
            inLanguage: "en",
            publisher: { "@id": `${SITE_URL}/#organization` },
          },
        ],
      }}
    />
  );
}
