"""The reviewed Tatva draft is the contract that Save Matrix freezes.

These tests use the real HTTP routes and a scratch Postgres database. Sutra's
initial proposal is generated by the scripted model in test_job_setup_live;
all subsequent changes are made through the Hiring Manager's public API.
"""
from __future__ import annotations

import asyncio
import uuid
from types import SimpleNamespace

import pytest
import sqlalchemy as sa

from app.models.enums import Role
from app.models.job_scorecard_binding import JobScorecardBinding
from app.services.hiring import drishti, scorecard
from tests.test_job_setup_live import (
    ASSESSMENTS,
    _assign,
    _compile,
    _create_job,
    _run_swot,
    _write_company_profile,
)

# THE FIXTURES ARE IMPORTED, NOT REGISTERED AS A PLUGIN, AND THE DIFFERENCE
# BROKE AN UNRELATED TEST FILE.
#
# This read `pytest_plugins = ("tests.test_job_setup_live",)`. Registering a
# module as a PLUGIN makes every fixture in it global for the whole session,
# and `_no_provider` is `autouse=True`: it monkeypatches
# `llm_router.invoke_llm` and `chat_completion` to a scripted stand-in. As a
# module-local fixture that is exactly right. Promoted session-wide it
# silently replaced the router underneath every test that ran afterwards, and
# `test_vendor_contracts.py` -- which asserts that a 400 carrying no known
# hazard still raises `LLMUnavailableError` -- stopped raising, because the
# function it was testing was no longer the function being called.
#
# It failed ONLY in a full-suite run. Both files passed alone, which is the
# signature this repository has already been bitten by once: the nineteen
# tests that passed in isolation and failed in the suite when a `sys.modules`
# fake stopped binding. Importing the fixture NAMES binds them to this module
# and nothing else, so the scripted provider covers the tests that need it and
# reaches no further.
#
# `world`, `sessions` and `client` are the chain this file's tests request;
# the three autouse fixtures are imported for their effect, and the noqa marks
# them as deliberately unused names rather than dead imports.
from tests.test_job_setup_live import (  # noqa: F401
    _no_dispatch,
    _no_permission_cache,
    _no_provider,
    client,
    sessions,
    world,
)


def _setup_draft(client, sessions) -> str:
    client.sign_in(Role.hr_manager)
    _write_company_profile(sessions, client.world.tenant_a)
    job_id = _create_job(client, f"Tatva Review {uuid.uuid4().hex[:8]}")
    _assign(sessions, job_id, client.world)
    client.sign_in(Role.recruiter)
    sent = client.post(f"/jobs/{job_id}/send-to-hiring-manager")
    assert sent.status_code == 200, sent.text
    client.sign_in(Role.hiring_manager)
    _run_swot(client, job_id)
    _compile(sessions, job_id)
    return job_id


def _framework(client, job_id: str) -> list[dict]:
    response = client.get(f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework")
    assert response.status_code == 200, response.text
    return response.json()["competencies"]


def _stored_contract(sessions, job_id: str) -> tuple[list[dict], list[JobScorecardBinding]]:
    async def _read():
        from app.core.db import superadmin_scope

        async with sessions() as session:
            async with session.begin():
                async with superadmin_scope(session):
                    rows = (
                        await session.execute(
                            sa.text(
                                "SELECT id, name, category, ordinal, required_level, "
                                "dimension, observable_evidence, assessment_method, "
                                "weight, threshold_json, provenance_json, is_active, "
                                "swot_origin "
                                "FROM job_competencies WHERE job_id = :job "
                                "ORDER BY category, ordinal"
                            ),
                            {"job": job_id},
                        )
                    ).mappings().all()
                    bindings = (
                        await session.execute(
                            sa.select(JobScorecardBinding).where(
                                JobScorecardBinding.job_id == uuid.UUID(job_id)
                            )
                        )
                    ).scalars().all()
                    return [dict(row) for row in rows], list(bindings)

    return asyncio.run(_read())


def test_human_add_rename_move_delete_are_frozen_exactly(client, sessions) -> None:
    job_id = _setup_draft(client, sessions)
    initial = _framework(client, job_id)
    assert initial

    # A new criterion starts without Sutra's derivation. This was the reported
    # "These criteria carry no derivation" failure on Save Matrix.
    added = client.post(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework",
        json={
            "category": "nice_to_have",
            "name": "Advanced RAG Architecture",
            "description": (
                "Has designed and shipped a retrieval system to production "
                "and can explain measured accuracy and latency."
            ),
            "required_level": "Highly Matching",
        },
    )
    assert added.status_code == 201, added.text
    added_id = added.json()["id"]

    renamed = next(row for row in initial if row["category"] == "must_have")
    new_name = "Production Retrieval Design"
    changed = client.put(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/{renamed['id']}",
        json={
            "category": renamed["category"],
            "name": new_name,
            "description": renamed["description"],
            "required_level": renamed["required_level"],
        },
    )
    assert changed.status_code == 200, changed.text

    removed = next(row for row in initial if row["category"] == "nice_to_have")
    deleted = client.http.delete(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/{removed['id']}"
    )
    assert deleted.status_code == 204, deleted.text

    # Moving the new criterion to Must-have is a human classification decision.
    before_move = _framework(client, job_id)
    must = [row["id"] for row in before_move if row["category"] == "must_have"]
    nice = [
        row["id"]
        for row in before_move
        if row["category"] == "nice_to_have" and row["id"] != added_id
    ]
    moved = client.post(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/reorder",
        json={
            "groups": [
                {"category": "must_have", "competency_ids": must + [added_id]},
                {"category": "nice_to_have", "competency_ids": nice},
            ]
        },
    )
    assert moved.status_code == 200, moved.text
    reviewed = _framework(client, job_id)
    expected = [(row["id"], row["name"], row["category"], row["ordinal"])
                for row in reviewed]
    assert any(row["name"] == new_name for row in reviewed)
    assert any(row["id"] == added_id and row["category"] == "must_have"
               for row in reviewed)
    assert all(row["id"] != removed["id"] for row in reviewed)

    final = client.post(f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/finalize")
    assert final.status_code == 200, final.text
    assert final.json()["approved"] is True
    assert [(row["id"], row["name"], row["category"], row["ordinal"])
            for row in final.json()["competencies"]] == expected

    stored, bindings = _stored_contract(sessions, job_id)
    active = [row for row in stored if row["is_active"]]
    assert {str(row["id"]) for row in active} == {row[0] for row in expected}
    assert all(row["weight"] is not None and row["weight"] > 0 for row in active)
    assert all(row["dimension"] and row["observable_evidence"] for row in active)
    assert all(row["assessment_method"] and row["threshold_json"] for row in active)
    assert all(row["provenance_json"] for row in active)
    assert len(bindings) == 1
    assert bindings[0].frozen_by == client.principal.user_id


def test_failed_enrichment_rolls_back_every_change(client, sessions, monkeypatch) -> None:
    job_id = _setup_draft(client, sessions)
    added = client.post(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework",
        json={
            "category": "must_have",
            "name": "Novel Retrieval Design",
            "required_level": "Highly Matching",
        },
    )
    assert added.status_code == 201, added.text
    before, bindings_before = _stored_contract(sessions, job_id)
    assert not bindings_before

    async def _fail_after_partial_enrichment(session, job, rows):
        rows[0].weight = 0.99
        rows[0].dimension = "verified_competence"
        await session.flush()
        raise scorecard.ScorecardInputMissing(
            "matrix", "Novel Retrieval Design needs observable evidence."
        )

    monkeypatch.setattr(scorecard, "_enrich_reviewed_rows", _fail_after_partial_enrichment)
    response = client.post(f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/finalize")
    assert response.status_code == 422, response.text
    assert "Novel Retrieval Design" in response.text
    after, bindings_after = _stored_contract(sessions, job_id)
    assert after == before
    assert not bindings_after
    assert all(row["weight"] is None for row in after if row["name"] == "Novel Retrieval Design")


def test_unassigned_hiring_manager_cannot_finalize(client, sessions) -> None:
    job_id = _setup_draft(client, sessions)
    client.sign_in(Role.recruiter)
    recruiter_refused = client.post(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/finalize"
    )
    assert recruiter_refused.status_code == 403, recruiter_refused.text
    client.sign_in(Role.hiring_manager, client.world.tenant_b)
    refused = client.post(f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/finalize")
    assert refused.status_code in (403, 404), refused.text
    _rows, bindings = _stored_contract(sessions, job_id)
    assert not bindings


def test_a_rename_does_not_carry_the_swot_sentence_onto_the_new_criterion(
    client, sessions
) -> None:
    """The renamed criterion must not keep the SWOT sentence it no longer means.

    `scorecard.plain_provenance` renders `swot_origin` back to the reviewer
    verbatim as `You said: "..."`. Sutra stamps it with the reporting
    authority's own sentence. Rename "Kubernetes operations" to "Incident
    command" and carrying the sentence across attributes a quotation about one
    criterion to a different one, on the single screen this contract exists to
    make trustworthy. A fabricated citation reads as provenance, which is why
    it is worse than no provenance at all.

    Note the asymmetry this pins: `_revive` deliberately KEEPS the derivation,
    because a name coming back is the same name and the sentence still refers
    to it. Only a change of name or category clears it.
    """
    job_id = _setup_draft(client, sessions)
    before, _ = _stored_contract(sessions, job_id)
    sourced = next(
        row for row in before if row["is_active"] and (row["swot_origin"] or "").strip()
    )

    changed = client.put(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/{sourced['id']}",
        json={
            "category": sourced["category"],
            "name": "Incident Command Under Load",
            "description": sourced["observable_evidence"],
            "required_level": "Highly Matching",
        },
    )
    assert changed.status_code == 200, changed.text

    after, _ = _stored_contract(sessions, job_id)
    renamed = next(row for row in after if row["id"] == sourced["id"])
    assert renamed["name"] == "Incident Command Under Load"
    assert not renamed["swot_origin"], renamed["swot_origin"]

    final = client.post(f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework/finalize")
    assert final.status_code == 200, final.text

    frozen, _ = _stored_contract(sessions, job_id)
    kept = next(row for row in frozen if row["id"] == sourced["id"])
    assert kept["name"] == "Incident Command Under Load"
    # Enrichment re-derived the technical stages without borrowing the old
    # sentence. An honest absence, not a transplanted quotation.
    assert not kept["swot_origin"], kept["swot_origin"]
    assert kept["dimension"] and kept["weight"] and kept["observable_evidence"]


def test_sutra_cannot_rebuild_over_a_criterion_the_team_added(client, sessions) -> None:
    """`replace=True` is the one way into the compiler that skips idempotence.

    The default path is safe already: a redelivered message finds active rows
    and returns them untouched. `replace=True` exists to rebuild a draft after
    the Job SWOT changed, and it rewrites name, category, requirement level
    and ordinal on every surviving row while soft-deleting anything the new
    build does not produce. The deprecated `pickready.generate_ppi_framework`
    alias forwards the flag, so a message sitting on the broker under the old
    name is a live route to it.

    Sutra proposes. It does not get to overrule the reviewer because a message
    arrived.
    """
    job_id = _setup_draft(client, sessions)
    added = client.post(
        f"{ASSESSMENTS}/assessments/jobs/{job_id}/framework",
        json={
            "category": "must_have",
            "name": "Advanced RAG Architecture",
            "required_level": "Highly Matching",
        },
    )
    assert added.status_code == 201, added.text
    before, _ = _stored_contract(sessions, job_id)

    with pytest.raises(scorecard.ScorecardInputMissing) as refusal:
        _compile(sessions, job_id)

    # The criterion is NAMED. "The matrix cannot be rebuilt" with no subject
    # leaves the reviewer with nothing to act on.
    assert "Advanced RAG Architecture" in str(refusal.value)

    after, _ = _stored_contract(sessions, job_id)
    assert after == before


def test_an_outage_during_enrichment_is_not_reported_as_a_bad_criterion(
    monkeypatch,
) -> None:
    """A provider that does not answer refuses EVERY pending phrase alike.

    `_name_unanchored` falls back to `{"named": [], "refused": []}`, so a
    degraded run produces one stock refusal per criterion. Reporting the first
    of them blames an arbitrary criterion for an outage and tells the hiring
    manager to rephrase something that is fine. They cannot fix it by editing,
    so they edit until the provider comes back. `degraded` is the only signal
    that separates the two cases.
    """
    job = SimpleNamespace(
        id=uuid.uuid4(),
        tenant_id=uuid.uuid4(),
        department="engineering",
        title="Staff Engineer",
        jd_markdown="Own the ingestion platform.",
        assessment_grade="managerial",
        about_company=None,
        work_life=None,
    )
    row = SimpleNamespace(
        id=uuid.uuid4(),
        name="Advanced RAG Architecture",
        category="must_have",
        dimension=None,
        weight=None,
        observable_evidence=None,
        evidence_sources=None,
        assessment_method=None,
        threshold_json=None,
        provenance_json=None,
        swot_origin=None,
    )

    async def _compiled_for(*_args, **_kwargs):
        return None, []

    async def _degraded(*_args, **_kwargs):
        return {}, [
            {
                "phrase": row.name,
                "category": row.category,
                "stage": "competency",
                "reason": "Sutra could not name a competency for this.",
            }
        ], True

    monkeypatch.setattr(drishti, "compiled_for", _compiled_for)
    monkeypatch.setattr(scorecard, "_name_unanchored", _degraded)

    with pytest.raises(scorecard.ScorecardInputMissing) as refusal:
        asyncio.run(scorecard._enrich_reviewed_rows(object(), job, [row]))

    message = str(refusal.value)
    assert "did not respond" in message
    assert "no criterion needs editing" in message
    # The criterion's name must NOT appear: naming it is what sends somebody
    # to edit a criterion that was never the problem.
    assert row.name not in message
    # And nothing was written on the way out.
    assert row.dimension is None and row.weight is None
