"""Report generation engine (Master Directive Part 4 section 3.1).

All reports are generated server-side; the client receives a completed file.
`generate` dispatches to the per-report builder, then renders the builder's
format-neutral content as PDF (ReportLab, ReadyPick navy branding) or CSV.

Every rendered report carries the standard header block the directive
requires: Report Name, Date Range, Organisation, Generated By, Generated At,
Report ID.

EXCEL IS EMITTED AS CSV IN THIS PASS. openpyxl is not in the environment
(verified: `import openpyxl` fails) and Part 4 gives no licence to ship a
heavy new dependency from a report route, so a request for the `excel` format
receives the same tabular data as CSV, which Excel opens natively. The
catalogue keeps declaring `excel` so the UI matches the directive's tables;
swap `_render_tabular` for an openpyxl writer when the dependency lands.
"""
from __future__ import annotations

import csv
import io
import uuid
from datetime import date, datetime, timezone
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.tenant import Tenant
from app.services.reports import catalogue
from app.services.reports.builders import BUILDERS, ReportContent, ReportParams


class UnknownReport(LookupError):
    """The report id is not in the Part 4 catalogue at all."""

    def __init__(self, report_id: str) -> None:
        super().__init__(f"Unknown report id: {report_id}")
        self.report_id = report_id


class ReportNotImplemented(NotImplementedError):
    """Catalogued (Part 4 lists it) but its builder has not shipped yet.

    The API maps this to 501 so the client learns the truthful thing: the
    report exists in the library and cannot be generated yet. The UI greys it
    out from the catalogue's `implemented` flag before anyone gets this far.
    """

    def __init__(self, report_id: str, name: str) -> None:
        super().__init__(
            f"Report {report_id} ({name}) is catalogued but not yet "
            "implemented; its builder has not shipped."
        )
        self.report_id = report_id
        self.name = name


class ReportComingSoon(ReportNotImplemented):
    """Conditionally activated (Part 4 section 4): the DEI report must not
    run until the client consent framework for demographic data exists."""

    def __init__(self, report_id: str, name: str) -> None:
        NotImplementedError.__init__(
            self,
            f"Report {report_id} ({name}) is marked Coming Soon: demographic "
            "data is not collected or processed until the client consent "
            "framework required by Part 4 section 4 is in place.",
        )
        self.report_id = report_id
        self.name = name


# ── ReadyPick branding (Part 4 section 3.1: navy header, consistent type) ────
NAVY = "#0A1F44"
NAVY_LIGHT = "#16305E"
PAPER = "#F5F7FB"
INK = "#172033"


def _parse_params(params: dict[str, Any] | None) -> ReportParams:
    """Coerce the request's parameter dict into the typed ReportParams.

    Dates accept ISO date or datetime strings; a bare date_to is widened to
    the END of that day so "to 2026-08-31" includes the 31st.
    """
    params = params or {}

    def _dt(key: str, end_of_day: bool) -> datetime | None:
        raw = params.get(key)
        if raw in (None, ""):
            return None
        if isinstance(raw, datetime):
            value = raw
        else:
            value = datetime.fromisoformat(str(raw))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        if end_of_day and (value.hour, value.minute, value.second) == (0, 0, 0):
            value = value.replace(hour=23, minute=59, second=59)
        return value

    job_id = params.get("job_id")
    return ReportParams(
        date_from=_dt("date_from", end_of_day=False),
        date_to=_dt("date_to", end_of_day=True),
        job_id=uuid.UUID(str(job_id)) if job_id else None,
        department=params.get("department") or None,
    )


async def generate(
    session: AsyncSession,
    tenant_id: uuid.UUID,
    report_id: str,
    params: dict[str, Any] | None,
    fmt: str,
) -> tuple[bytes, str, str]:
    """Generate one report; returns (content bytes, media type, filename).

    Refuses before touching the database: an unknown id, a Coming Soon
    report, and an unimplemented report all fail without a query, so the
    engine's contract can be tested with no session at all.
    """
    defn = catalogue.definition_for(report_id)
    if defn is None:
        raise UnknownReport(report_id)
    if defn.coming_soon:
        raise ReportComingSoon(defn.id, defn.name)
    if not defn.implemented or defn.id not in BUILDERS:
        raise ReportNotImplemented(defn.id, defn.name)

    fmt = (fmt or "pdf").lower()
    if fmt not in ("pdf", "excel", "csv"):
        raise ValueError(f"Unsupported format: {fmt}")

    parsed = _parse_params(params)
    content = await BUILDERS[defn.id](session, tenant_id, parsed)

    tenant = await session.get(Tenant, tenant_id)
    header = _header_lines(
        defn,
        parsed,
        organisation=(tenant.name if tenant else ""),
        generated_by=str((params or {}).get("generated_by") or ""),
    )

    stamp = date.today().isoformat()
    if fmt == "pdf":
        data = _render_pdf(defn, header, content)
        return data, "application/pdf", f"{defn.id.lower()}-{stamp}.pdf"
    # excel falls through to CSV deliberately; see the module docstring.
    data = _render_tabular(header, content)
    return data, "text/csv", f"{defn.id.lower()}-{stamp}.csv"


def _header_lines(
    defn: catalogue.ReportDefinition,
    parsed: ReportParams,
    *,
    organisation: str,
    generated_by: str,
) -> list[tuple[str, str]]:
    """The standard header block (Part 4 section 3.1), field for field."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return [
        ("Report Name", f"{defn.id}  {defn.name}"),
        ("Date Range", parsed.range_label()),
        ("Organisation", organisation or "-"),
        ("Generated By", generated_by or "-"),
        ("Generated At", generated_at),
        ("Report ID", uuid.uuid4().hex),
    ]


# ── CSV / "excel" rendering ──────────────────────────────────────────────────

def _render_tabular(
    header: list[tuple[str, str]], content: ReportContent
) -> bytes:
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\r\n")
    for key, value in header:
        writer.writerow([key, value])
    writer.writerow([])
    if content.summary:
        writer.writerow(["Summary"])
        for key, value in content.summary:
            writer.writerow([key.strip(), value])
        writer.writerow([])
    for table in content.tables:
        if table.title:
            writer.writerow([table.title])
        writer.writerow(table.columns)
        writer.writerows(table.rows)
        writer.writerow([])
    for note in content.notes:
        writer.writerow(["Note", note])
    # BOM so Excel opens the file as UTF-8 rather than the locale codepage.
    return out.getvalue().encode("utf-8-sig")


# ── PDF rendering ────────────────────────────────────────────────────────────

def _render_pdf(
    defn: catalogue.ReportDefinition,
    header: list[tuple[str, str]],
    content: ReportContent,
) -> bytes:
    # Imported here, not at module top: ReportLab is heavy, and every caller
    # of the catalogue (RBAC filtering, tests, the API's /catalog route)
    # should not pay for a PDF engine it may never use in that process.
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
    from xml.sax.saxutils import escape

    navy = colors.HexColor(NAVY)
    navy_light = colors.HexColor(NAVY_LIGHT)
    paper = colors.HexColor(PAPER)
    ink = colors.HexColor(INK)

    body = ParagraphStyle(
        "body", fontName="Helvetica", fontSize=8, leading=10, textColor=ink
    )
    cell_head = ParagraphStyle(
        "cell_head", parent=body, fontName="Helvetica-Bold",
        textColor=colors.white,
    )
    note_style = ParagraphStyle(
        "note", parent=body, fontSize=7.5, textColor=colors.HexColor("#64748B")
    )
    h_title = ParagraphStyle(
        "h_title", fontName="Helvetica-Bold", fontSize=15, leading=18,
        textColor=colors.white,
    )
    h_sub = ParagraphStyle(
        "h_sub", fontName="Helvetica", fontSize=8.5, leading=11,
        textColor=colors.HexColor("#C9D4EA"),
    )
    section = ParagraphStyle(
        "section", fontName="Helvetica-Bold", fontSize=10, leading=13,
        textColor=navy, spaceBefore=6,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=14 * mm, rightMargin=14 * mm,
        topMargin=12 * mm, bottomMargin=14 * mm,
        title=f"{defn.id} {defn.name}", author="ReadyPick",
    )
    width = doc.width
    story: list = []

    # Navy banner: brand + report identity (section 3.1).
    banner = Table(
        [
            [Paragraph("READYPICK", h_sub)],
            [Paragraph(escape(f"{defn.id}  {defn.name}"), h_title)],
            [Paragraph(escape(catalogue.CATEGORIES.get(defn.category, "")), h_sub)],
        ],
        colWidths=[width],
    )
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), navy),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 8),
    ]))
    story.append(banner)
    story.append(Spacer(1, 4 * mm))

    # Standard header block, two columns.
    head_rows = [
        [Paragraph(f"<b>{escape(k)}</b>", body), Paragraph(escape(v), body)]
        for k, v in header
    ]
    head_table = Table(head_rows, colWidths=[width * 0.22, width * 0.78])
    head_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), paper),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#DDE3EF")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(head_table)
    story.append(Spacer(1, 5 * mm))

    if content.summary:
        story.append(Paragraph("Summary", section))
        summary_rows = [
            [Paragraph(escape(k), body), Paragraph(f"<b>{escape(v)}</b>", body)]
            for k, v in content.summary
        ]
        summary_table = Table(summary_rows, colWidths=[width * 0.55, width * 0.45])
        summary_table.setStyle(TableStyle([
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, paper]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 3 * mm))

    for table in content.tables:
        if table.title:
            story.append(Paragraph(escape(table.title), section))
            story.append(Spacer(1, 1.5 * mm))
        data = [[Paragraph(escape(c), cell_head) for c in table.columns]]
        for row in table.rows:
            data.append([Paragraph(escape(str(cell)), body) for cell in row])
        if len(data) == 1:
            data.append([Paragraph("No rows in the selected range.", note_style)]
                        + [Paragraph("", body)] * (len(table.columns) - 1))
        pdf_table = Table(
            data, colWidths=[width / len(table.columns)] * len(table.columns),
            repeatRows=1,
        )
        pdf_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), navy_light),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, paper]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#DDE3EF")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(pdf_table)
        story.append(Spacer(1, 4 * mm))

    for note in content.notes:
        story.append(Paragraph(escape(note), note_style))

    doc.build(story)
    return buffer.getvalue()
