/**
 * ElastiCache for Redis: shared counters, run status, and the cache layer.
 *
 * REDIS IS NOT ONLY A CACHE HERE, AND THAT CHANGES EVERY SETTING BELOW.
 *
 * IT STOPPED BEING THE MESSAGE BROKER on 2026-09-04, when background work moved
 * to Lambda and on-demand Fargate. That made this module's settings MORE
 * carefully chosen rather than less, because what is left is not
 * interchangeable with a cache:
 *
 *   the proctoring warning counter   one shared counter per session, across
 *                                    every event type. The server decides, and
 *                                    `services/proctoring/gate` answers 503
 *                                    rather than silently not warning, so a
 *                                    lost counter is a refused assessment turn.
 *   the rate limiter                 shared fixed-window counters. It fails
 *                                    OPEN by design, so this one degrades
 *                                    quietly and correctly.
 *   the background run status        what the matching stage list and the
 *                                    outreach delivery modal poll. A lost
 *                                    record reads as "pending" for ever.
 *   the caches                       job descriptions, company profiles,
 *                                    price lists, candidate profiles.
 *
 * Two consequences follow:
 *
 *   * `automatic_failover_enabled` and a replica in production. A single node
 *     is a single AZ away from an outage that refuses every assessment turn.
 *   * `maxmemory-policy` is `noeviction`, NOT `allkeys-lru`. The default LRU
 *     policy is correct for a pure cache and wrong for this: under memory
 *     pressure Redis would evict a live assessment's warning counter, silently
 *     resetting a candidate's warnings to zero mid-assessment, and evict the
 *     run-status record a recruiter is watching. `noeviction` makes the WRITE
 *     fail instead, which every writer here already handles and which is loud.
 *
 * THE AUTH TOKEN IS GENERATED BY AWS AND NEVER ENTERS TERRAFORM STATE.
 * `aws_elasticache_replication_group` has no managed-password equivalent to
 * RDS's, so the token is supplied out of band and referenced by secret ARN.
 * A `random_password` here would put the credential in the state file.
 *
 * TRANSIT ENCRYPTION IS ON, WHICH MEANS THE CLIENT MUST USE `rediss://`.
 * That is a real constraint on the application rather than a free win, and it
 * is stated here because the failure mode -- a client that connects with
 * `redis://` and hangs -- looks like a network problem rather than a scheme
 * problem.
 */

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.60"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5"
    }
  }
}

locals {
  name = "${var.project}-${var.environment}"
}

resource "aws_elasticache_subnet_group" "this" {
  name       = local.name
  subnet_ids = var.subnet_ids

  tags = merge(var.tags, { Name = local.name })
}

resource "aws_elasticache_parameter_group" "this" {
  name   = "${local.name}-redis7"
  family = "redis7"

  # THE ONE THAT MATTERS. See the module docstring: `allkeys-lru` would evict,
  # under memory pressure and without a word, a live assessment's proctoring
  # warning counter and the run-status record a recruiter is watching. The
  # symptom is a candidate's warnings silently back at zero and a finished run
  # that still reads as pending. `noeviction` makes the write fail loudly.
  parameter {
    name  = "maxmemory-policy"
    value = "noeviction"
  }

  tags = var.tags
}

# GENERATED, NEVER PASSED IN.
#
# An `auth_token` variable would be a credential travelling through a tfvars
# file, a CI variable and a shell, which is the shape
# `test_deploy_secret_hygiene.py` exists to refuse. Generating it here means it
# exists in exactly two places: the Terraform state, which is the encrypted,
# access-controlled S3 bucket the runbook creates in its first step, and
# ElastiCache itself.
#
# The operator composes REDIS_URL from `terraform output -raw redis_auth_token`
# and writes it into Secrets Manager. See `docs/DEPLOY_AWS.md`.
#
# `keepers` is deliberately empty: without it, any change to this resource's
# arguments regenerates the token and every running worker loses its broker at
# once. Rotation is a deliberate act, documented in the runbook, not a side
# effect of an unrelated apply.
resource "random_password" "auth_token" {
  # ElastiCache accepts 16 to 128 characters and rejects several punctuation
  # marks outright, so the character set is stated rather than defaulted: a
  # generated token containing a forbidden character fails at apply time with an
  # error that names the parameter and not the character.
  length           = 64
  special          = true
  override_special = "!&#$^<>-"
}

resource "aws_elasticache_replication_group" "this" {
  replication_group_id = local.name
  description          = "ReadyPick ${var.environment}: shared counters, run status and cache"

  engine               = "redis"
  engine_version       = var.engine_version
  node_type            = var.node_type
  parameter_group_name = aws_elasticache_parameter_group.this.name
  port                 = 6379

  subnet_group_name  = aws_elasticache_subnet_group.this.name
  security_group_ids = [var.security_group_id]

  num_cache_clusters = 1 + var.replica_count

  # Failover needs a replica to fail over TO, so the two settings move together.
  # Stated as a derived expression rather than as a separate variable, because
  # `automatic_failover_enabled = true` with zero replicas is a configuration
  # that reads as resilient and is not.
  automatic_failover_enabled = var.replica_count > 0
  multi_az_enabled           = var.replica_count > 0

  at_rest_encryption_enabled = true
  kms_key_id                 = var.kms_key_arn

  # Transit encryption means the client must use `rediss://`. A client that
  # connects with `redis://` hangs, and the symptom looks like a network
  # problem rather than a scheme problem -- see the module docstring.
  transit_encryption_enabled = true

  # AN AUTH TOKEN, NOT JUST A SECURITY GROUP.
  #
  # Encryption in transit without authentication means anything that can reach
  # port 6379 inside this VPC can read the queue, and "anything in this VPC" is
  # a set that grows with whatever gets deployed here next year. The security
  # group narrows it to the task security group today; the token is what makes
  # the narrowing a property of the broker rather than of the network around it.
  #
  # It also closes an inconsistency this repository was already carrying:
  # `backend/tests/test_deploy_secret_hygiene.py` lists REDIS_URL as a
  # CREDENTIAL, with the stated reason that "on ElastiCache with transit
  # encryption and an AUTH token it carries the token". The token did not exist.
  # The test's classification was right and the infrastructure had not caught up.
  auth_token                 = random_password.auth_token.result
  auth_token_update_strategy = "ROTATE"

  # A snapshot of a BROKER is close to worthless -- the queue's contents at 3am
  # are not something anybody restores. It is on in production anyway because
  # the working-memory layer shares the instance, and one retained day is the
  # cheapest possible hedge against needing it.
  snapshot_retention_limit = var.environment == "production" ? 1 : 0
  snapshot_window          = "18:00-19:00"
  maintenance_window       = "sun:19:30-sun:20:30"

  auto_minor_version_upgrade = true
  apply_immediately          = var.environment != "production"

  tags = merge(var.tags, { Name = local.name })

  lifecycle {
    ignore_changes = [engine_version]
  }
}
