"""AI matching pipeline endpoints (FR-4.2/4.5). Matching itself always runs
as the dispatched `pickready.run_matching` task — never inline (ESD §17)."""
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import CurrentUser, get_tenant_db, require_capability
from app.models.candidate import Candidate, JobCandidateLink, source_type_label
from app.models.job import Job
from app.models.job_setup import JobMatchingCategory
from app.schemas.candidates import CandidateOut
from app.schemas.matching import (
    MatchingCategoriesOut,
    MatchingCategoryIn,
    MatchingCategoryOut,
    MatchingStageOut,
    MatchingTaskStatusOut,
    MatchResultOut,
    MatchResultsOut,
    RunMatchingOut,
)
from app.services import capabilities as caps
from app.services import matching_categories, matching_progress
from app.services.audit import audit
from app.services.matching import client_breakdown, ranking_payload
from app.workers import status as task_status
from app.workers.dispatch import dispatch

router = APIRouter()


async def _get_job(session: AsyncSession, user: CurrentUser, job_id: uuid.UUID) -> Job:
    job = await session.get(Job, job_id)
    if job is None or job.tenant_id != user.tenant_id:  # defense in depth; RLS is the boundary
        raise HTTPException(status_code=404, detail="Job not found")
    return job


@router.post(
    "/jobs/{job_id}/run",
    response_model=RunMatchingOut,
    status_code=status.HTTP_202_ACCEPTED,
)
async def run_matching(
    job_id: uuid.UUID,
    user: CurrentUser = Depends(require_capability(caps.TRIGGER_MATCHING)),
    session: AsyncSession = Depends(get_tenant_db),
) -> RunMatchingOut:
    job = await _get_job(session, user, job_id)
    if job.ratified_at is None:
        raise HTTPException(status_code=409, detail="Matching runs once the job is ratified (FR-3.4)")
    if job.archived_at is not None:
        raise HTTPException(status_code=409, detail="Restore this job before running matching")
    if job.assessment_status != "ready_for_candidates":
        raise HTTPException(
            status_code=409,
            detail=(
                "Finish the job setup review before running matching. The PPI "
                "matrix and the matching categories both need to be saved."
            ),
        )
    candidate_count = (
        await session.execute(
            select(func.count(JobCandidateLink.id)).where(
                JobCandidateLink.job_id == job.id
            )
        )
    ).scalar_one()
    task = dispatch("pickready.run_matching", args=[str(job.id)])
    await audit(session, tenant_id=user.tenant_id, actor_user_id=user.user_id,
                action="matching_triggered", target_type="job", target_id=job.id)
    return RunMatchingOut(
        job_id=job.id,
        task_id=task.id,
        candidate_count=candidate_count,
    )


# ── The job's Matching category list (spec §3.2) ─────────────────────────────
# Generated by the AI at job creation, then added to, modified, replaced or
# removed by the recruiter, with a minimum of five enforced HERE rather than
# only in the UI. Once finalised the list applies automatically to every
# candidate sourced for the job, with no per-candidate step.


def _category_out(row: JobMatchingCategory) -> MatchingCategoryOut:
    return MatchingCategoryOut(
        id=row.id,
        key=row.key,
        name=row.name,
        description=row.description,
        ordinal=row.ordinal,
    )


async def _categories_out(session: AsyncSession, job: Job) -> MatchingCategoriesOut:
    rows = await matching_categories.list_categories(session, job.id)
    ok, reason = matching_categories.categories_are_complete(rows)
    return MatchingCategoriesOut(
        job_id=job.id,
        finalized=job.matching_categories_finalized_at is not None,
        categories=[_category_out(row) for row in rows],
        minimum=matching_categories.MINIMUM_CATEGORIES,
        maximum=matching_categories.MAXIMUM_CATEGORIES,
        blocking_reason=None if ok else reason,
    )


def _reject_finalized(job: Job) -> None:
    """A finalised list is what every candidate on the job was ranked against.

    Refused rather than versioned, for the same reason a saved PPI matrix is
    frozen: two candidates ranked against different category lists are not
    comparable, and the AI Score on an existing report states grades against
    the list that was in force when it was written.
    """
    if job.matching_categories_finalized_at is not None:
        raise HTTPException(
            status_code=409,
            detail=(
                "These matching categories are saved and candidates have been "
                "ranked against them. Changing them now would make two "
                "candidates on this job impossible to compare."
            ),
        )


@router.get("/jobs/{job_id}/categories", response_model=MatchingCategoriesOut)
async def list_matching_categories(
    job_id: uuid.UUID,
    user: CurrentUser = Depends(require_capability(caps.CREATE_JOB)),
    session: AsyncSession = Depends(get_tenant_db),
) -> MatchingCategoriesOut:
    job = await _get_job(session, user, job_id)
    # Self-healing read, the same shape the PPI matrix uses and for the same
    # reason: a generation that never landed would otherwise render as a
    # finished, empty list and nothing anywhere would retry it.
    if not await matching_categories.list_categories(session, job.id):
        dispatch(
            "pickready.generate_matching_categories", args=[str(job.id)]
        )
    return await _categories_out(session, job)


@router.post(
    "/jobs/{job_id}/categories",
    response_model=MatchingCategoryOut,
    status_code=status.HTTP_201_CREATED,
)
async def add_matching_category(
    job_id: uuid.UUID,
    body: MatchingCategoryIn,
    user: CurrentUser = Depends(require_capability(caps.CREATE_JOB)),
    session: AsyncSession = Depends(get_tenant_db),
) -> MatchingCategoryOut:
    job = await _get_job(session, user, job_id)
    _reject_finalized(job)
    rows = await matching_categories.list_categories(session, job.id)
    if len(rows) >= matching_categories.MAXIMUM_CATEGORIES:
        raise HTTPException(
            status_code=422,
            detail=(
                f"A job is matched on at most "
                f"{matching_categories.MAXIMUM_CATEGORIES} categories. Every one "
                "of them costs a written comment on every candidate, and a "
                "longer list stops being a shortlist."
            ),
        )
    key = matching_categories.slugify(body.name)
    if any(row.key == key for row in rows):
        raise HTTPException(
            status_code=409, detail="This job already has a category with that name."
        )
    row = JobMatchingCategory(
        tenant_id=job.tenant_id,
        job_id=job.id,
        key=key,
        name=body.name,
        description=body.description,
        ordinal=(max((r.ordinal for r in rows), default=0) + 1),
    )
    session.add(row)
    await session.flush()
    return _category_out(row)


@router.put("/jobs/{job_id}/categories/{category_id}", response_model=MatchingCategoryOut)
async def update_matching_category(
    job_id: uuid.UUID,
    category_id: uuid.UUID,
    body: MatchingCategoryIn,
    user: CurrentUser = Depends(require_capability(caps.CREATE_JOB)),
    session: AsyncSession = Depends(get_tenant_db),
) -> MatchingCategoryOut:
    job = await _get_job(session, user, job_id)
    _reject_finalized(job)
    row = await session.get(JobMatchingCategory, category_id)
    if row is None or row.job_id != job.id:
        raise HTTPException(status_code=404, detail="Category not found")
    # The KEY does not move when the name does. It is what a score is filed
    # under, so renaming a category has to be a display change or every score
    # already written against it is orphaned.
    row.name = body.name
    row.description = body.description
    matching_categories.touch(row)
    await session.flush()
    return _category_out(row)


@router.delete(
    "/jobs/{job_id}/categories/{category_id}", status_code=status.HTTP_204_NO_CONTENT
)
async def remove_matching_category(
    job_id: uuid.UUID,
    category_id: uuid.UUID,
    user: CurrentUser = Depends(require_capability(caps.CREATE_JOB)),
    session: AsyncSession = Depends(get_tenant_db),
) -> None:
    job = await _get_job(session, user, job_id)
    _reject_finalized(job)
    row = await session.get(JobMatchingCategory, category_id)
    if row is None or row.job_id != job.id:
        raise HTTPException(status_code=404, detail="Category not found")
    # Soft delete: a candidate may already carry a score filed under this key,
    # and the report has to keep rendering it.
    row.is_active = False
    matching_categories.touch(row)
    await session.flush()


@router.post("/jobs/{job_id}/categories/finalize", response_model=MatchingCategoriesOut)
async def finalize_matching_categories(
    job_id: uuid.UUID,
    user: CurrentUser = Depends(require_capability(caps.CREATE_JOB)),
    session: AsyncSession = Depends(get_tenant_db),
) -> MatchingCategoriesOut:
    """Save the list, and move the job on if the PPI matrix is saved too.

    The two halves of the setup session are finalised independently and in
    either order; whichever one lands second is the one that opens the job to
    candidates. `_refresh_setup_status` owns that rule, so this route does not
    restate it.
    """
    from app.api.assessments import _refresh_setup_status

    job = await _get_job(session, user, job_id)
    rows = await matching_categories.list_categories(session, job.id)
    ok, reason = matching_categories.categories_are_complete(rows)
    if not ok:
        raise HTTPException(status_code=422, detail=reason)
    job.matching_categories_finalized_at = datetime.now(timezone.utc)
    await _refresh_setup_status(session, job)
    await audit(
        session,
        tenant_id=user.tenant_id,
        actor_user_id=user.user_id,
        action="matching_categories_finalized",
        target_type="job",
        target_id=job.id,
        metadata={"categories": [row.key for row in rows]},
    )
    return await _categories_out(session, job)


@router.get("/tasks/{task_id}", response_model=MatchingTaskStatusOut)
async def matching_task_status(
    task_id: str,
    _user: CurrentUser = Depends(require_capability(caps.TRIGGER_MATCHING)),
) -> MatchingTaskStatusOut:
    result = await task_status.read(task_id)
    # The stage list the job page renders inline while the run is under way.
    #
    # `result.payload` is what the run last published. It is only a stage
    # payload while the run is in the PROGRESS state -- on SUCCESS it is the
    # return value, and on FAILURE it is empty with the exception CLASS NAME
    # recorded beside it, because rendering an exception as stages would put a
    # traceback on a recruiter's screen. A run nothing has picked up yet
    # returns the full list in `pending`, so the page draws the plan
    # immediately rather than discovering it one row at a time.
    info = (
        result.payload if result.state == matching_progress.STATE_PROGRESS else None
    )
    payload = (
        info
        if isinstance(info, dict) and isinstance(info.get("stages"), list)
        else matching_progress.empty_payload()
    )
    return MatchingTaskStatusOut(
        task_id=task_id,
        state=result.state,
        done=result.done,
        stages=[MatchingStageOut(**stage) for stage in payload["stages"]],
        candidate_count=int(payload.get("candidate_count") or 0),
        scored_count=int(payload.get("scored_count") or 0),
    )


@router.get("/jobs/{job_id}/results", response_model=MatchResultsOut)
async def matching_results(
    job_id: uuid.UUID,
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=25, ge=1, le=100),
    user: CurrentUser = Depends(require_capability(caps.VIEW_DATABANK)),
    session: AsyncSession = Depends(get_tenant_db),
) -> MatchResultsOut:
    job = await _get_job(session, user, job_id)
    total = (
        await session.execute(
            select(func.count())
            .select_from(JobCandidateLink)
            .where(JobCandidateLink.job_id == job.id)
        )
    ).scalar_one()
    # One joined query, not one query per candidate. The ORDER BY carries an
    # explicit `id` tiebreak so the page boundary is stable: without a total
    # order, two links with the same score can swap places between requests and
    # one of them disappears from the paginated result entirely.
    rows = (
        await session.execute(
            select(JobCandidateLink, Candidate)
            .join(Candidate, Candidate.id == JobCandidateLink.candidate_id)
            .where(JobCandidateLink.job_id == job.id)
            .order_by(
                JobCandidateLink.match_score.desc().nulls_last(),
                JobCandidateLink.id,
            )
            .offset((page - 1) * page_size)
            .limit(page_size)
        )
    ).all()
    results: list[MatchResultOut] = []
    for link, candidate in rows:
        results.append(MatchResultOut(
            link_id=link.id,
            candidate=CandidateOut.model_validate(candidate),
            source=link.source,
            source_type=link.source_type,
            source_type_label=source_type_label(link.source_type),
            tier=link.tier,
            rationale=link.match_rationale,
            # Numeric parameter scores stay internal (claude.md).
            breakdown=client_breakdown(link.match_breakdown_json),
            # Comments-only projection (always present; see services.matching).
            **ranking_payload(link.match_breakdown_json),
        ))
    total_pages = max(1, (int(total) + page_size - 1) // page_size)
    return MatchResultsOut(
        job_id=job.id,
        results=results,
        total=int(total),
        page=page,
        page_size=page_size,
        total_pages=total_pages,
        has_next=page < total_pages,
        has_previous=page > 1,
    )
